// <auto-generated />
namespace SleeperCell.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SaleOrder_Stock_AndRelationCreated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SaleOrder_Stock_AndRelationCreated));
        
        string IMigrationMetadata.Id
        {
            get { return "201901281032086_SaleOrder_Stock_AndRelationCreated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
